"use client";
import Link from "next/link";
import React, { useState } from "react";
import Feather from "../components/Feather";
import Ionicons from "../components/Ionicons";
import LucideIcons from "../components/LucideIcons";
import TablerIcons from "../components/TablerIcons";
import ChevronIcon from "../components/ChevronIcon";
import Tabs from "../components/Tabs";
const Cards = [
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/feather/wind.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/feather/wind.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/feather/wind.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/feather/wind.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
];

const Cards1 = [
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/tabler-icons/device-heart-monitor.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/feather/wind.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/feather/wind.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/feather/zoom-in.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
];
const Cards2 = [
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/feather/wind.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/feather/wind.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
];
const Cards3 = [
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/navigate-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/planet-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/newspaper-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/person-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/people-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/partly-sunny-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image: "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power-sharp.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/power.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/musical-notes-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/play-skip-forward-circle.svg",
  },

  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag-outline.svg",
  },
  {
    image:
      "https://figma-library.s3.us-west-1.amazonaws.com/ionicons/pricetag.svg",
  },
];

const Page = () => {
  const [tab, setTab] = useState(1);
  const [filtered, setfiltered] = useState(
    tab === 1 ? Cards : tab === 2 ? Cards1 : tab === 3 ? Cards2 : Cards3
  );
  const handleSearch = (e) => {
    let query = e.target.value;
    let filtered = (
      tab === 1 ? Cards : tab === 2 ? Cards1 : tab === 3 ? Cards2 : Cards3
    ).filter((user) => user.image.includes(query));
    setfiltered(filtered);
  };
  return (
    <div className="flex justify-center ">
    <div className="flex flex-col px-6  gap-8 w-full">
     <div className="md:flex flex-wrap max-w-[1427px] items-center gap-x-6  justify-between ">
       <div className="pt-20 pb-16 px-16 gap-5 justify-start flex flex-wrap">
         <h1 className="font-extrabold text-2xl leading-5 not-italic">
              Open source icon libraries simplified
            </h1>
            <p>
              We’ve collected open source icon libraries and made it easy to get
              your favourite icons copy pasted directly in figma. Search for the
              icon & copy/paste in figma.
            </p>
          </div>
          <div className="flex w-full justify-end lg:absolute top-[100px] right-16">
            <img
              src="https://figmalibrary.com/wp-content/themes/figmalib/images/icons-page.svg"
              alt="img"
            />
          </div>
        </div>
        <div className="flex justify-between items-center  rounded-lg relative border border-[#e5e7eb]">
          <input  onChange={handleSearch}
            class="placeholder: placeholder:text-[#6b7280] block bg-white w-full border border-slate-300 rounded-md py-2 pl-9 pr-3 shadow-sm focus:outline-none focus:border-gray-500 focus:ring-gray-500 focus:ring-1 sm:text-xs font-medium"
            placeholder="Search..."
            type="text"
            name="search"
            className="py-3 px-4 w-full rounded-lg"
          />
          <img src="/test.img/Vector.png" className="absolute right-7" alt="img"/>
         
        </div>
        <div className="md:flex text-sm text-[#6b7280] font-normal justify-between gap-20">
          <>
            <Tabs
              tab={tab}
              setTab={(tab) => {
                setfiltered(tab === 1 ? Cards : tab === 2 ? Cards1 : Cards2);
                setTab(tab);
              }}
              tabs={[
                { title: "Feather" },
                { title: "Ionicons" },
                { title: "LucideIcons" },
                { title: "TablerIcons" },
              ]}
            />
          </>
          {/* <div className="flex items-center justify-end ">
            <ChevronIcon />
          </div> */}
        </div>
        {tab === 1 ? (
          <Feather Cards={filtered} />
        ) : tab === 2 ? (
          <Ionicons Cards={filtered} />
        ) : tab === 3 ? (
          <LucideIcons Cards={filtered} />
        ) : (
          <TablerIcons Cards={filtered} />
        )}
      </div>
    </div>
  );
};

export default Page;
