
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Sidebar from "./components/Sidebar";
import VerticalMenu from "./components/VerticalMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
 
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={`flex h-[100hv] `}>
          <Sidebar />
          
          <div className="md:flex flex-col w-full w:calc(100%-149px) overflow-y">
             <div className="">
             <div className="font-bold flex px-8 pt-8"> <Link href="/components">Home</Link></div> 
          <div className="sm:hidden">
            <VerticalMenu />
             
            </div> 

         
             
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
