import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Home from "./components/page";
// import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Icons = [
  { image: "/test.img/grid.svg", href: "/components", title: "Components" },
  { image: "/test.img/documents.svg", href: "/templates", title: "Templates" },
  { image: "/test.img/shapes.svg", href: "/icons", title: "Icons" },
  {
    image: "/test.img/monitor-mobbile.png",
    href: "/mockups",
    title: "Mockups",
  },
  { image: "/test.img/edit-2.png", href: "/content", title: "Content" },
];
export default function RootLayout({ children }) {
  
  // const pathname = usePathname()
  // console.log({pathname})
 return (
    <html lang="en">
      <body className={inter.className}>
        <div className={` flex h-[100hv] justify-center`}>
          <div className="side left-20 flex flex-col gap-10  py-20 ">
            <div className="flex fixed flex-col gap-4 justify-center items-center">
              <img src="/test.img/Group 812382.png" alt="img" />
              <h1 className="font-bold text-sm">Figma Library</h1>
              <p className="font-normal text-xs py-2">DESIGN 10X FASTER</p>
            </div>

            <div className="flex py-40 fixed flex-col gap-4 dalay-100">
              {Icons.map((items) => (
                <div className="   ">
                  <Link href={items.href} className= 'flex flex-col justify-center  items-center hover:bg-gray-200 active:bg-gray-900 active:text-white rounded-lg py-4 px-2 duration-300'>
                    <>
                      <img src={items.image} /> {items.title}
                    </>
                  </Link>
                </div>
              ))}
            </div>
          </div>

          <div className="container w:calc(100%-149px) justify-between overflow-y ">
            <div className="flex py-10 text-lg font-bold border px-4">  <Link href="/Home">Home</Link><p> » </p></div>
            {children}</div>
        </div>
      </body>
    </html>
  );
}
